/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIEW;

import DAL.ModuloConexao;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


public class TelaOcorrencia extends javax.swing.JInternalFrame {

    Connection conexao = null;      // abre conexao
    PreparedStatement pst = null;   //Executa Sql
    ResultSet rs = null;

    public TelaOcorrencia() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOcoCad = new javax.swing.JButton();
        btnOcoPes = new javax.swing.JButton();
        btnOcoEdi = new javax.swing.JButton();
        btnOcoEx = new javax.swing.JButton();
        btnOcoImp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtlocal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOcorrencia = new javax.swing.JTable();
        txtCodigo = new javax.swing.JTextField();
        txtData = new javax.swing.JFormattedTextField();
        txtDescricao = new javax.swing.JTextField();

        setTitle("Funcionalidade de Ocorrencias");
        setPreferredSize(new java.awt.Dimension(619, 490));

        btnOcoCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/add.png"))); // NOI18N
        btnOcoCad.setToolTipText("");
        btnOcoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcoCadActionPerformed(evt);
            }
        });

        btnOcoPes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/pesquisar.png"))); // NOI18N
        btnOcoPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcoPesActionPerformed(evt);
            }
        });

        btnOcoEdi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/editar.png"))); // NOI18N
        btnOcoEdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcoEdiActionPerformed(evt);
            }
        });

        btnOcoEx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/remover.png"))); // NOI18N
        btnOcoEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcoExActionPerformed(evt);
            }
        });

        btnOcoImp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/userImpressora.png"))); // NOI18N

        jLabel1.setText("Codigo");

        jLabel3.setText("Data");

        jLabel4.setText("Local");

        jLabel7.setText("Descrição");

        tblOcorrencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOcorrencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOcorrenciaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOcorrencia);

        txtCodigo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtData.setToolTipText("");

        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtlocal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOcoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOcoPes, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOcoEdi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOcoEx, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOcoImp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtlocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOcoPes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOcoCad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOcoEdi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOcoEx, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOcoImp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOcoPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcoPesActionPerformed
        // TODO add your handling code here:
        consultar();
    }//GEN-LAST:event_btnOcoPesActionPerformed

    private void btnOcoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcoCadActionPerformed
        // TODO add your handling code here:
        cadastrar();
    }//GEN-LAST:event_btnOcoCadActionPerformed

    private void tblOcorrenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOcorrenciaMouseClicked
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_tblOcorrenciaMouseClicked

    private void btnOcoExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcoExActionPerformed
        // TODO add your handling code here:
        remover();
    }//GEN-LAST:event_btnOcoExActionPerformed

    private void btnOcoEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcoEdiActionPerformed
        // TODO add your handling code here:
        atualizar();
    }//GEN-LAST:event_btnOcoEdiActionPerformed

    private void txtDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyReleased
        // TODO add your handling code here:
        buscar_dados_ocorrencias();
    }//GEN-LAST:event_txtDescricaoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOcoCad;
    private javax.swing.JButton btnOcoEdi;
    private javax.swing.JButton btnOcoEx;
    private javax.swing.JButton btnOcoImp;
    private javax.swing.JButton btnOcoPes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOcorrencia;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtlocal;
    // End of variables declaration//GEN-END:variables

     private void cadastrar() {

        String sql = "INSERT INTO e3ocorrencia (DATA, DESCRICAO, LOCAL) "
              + " VALUES ( ?, ?, ?)";

        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtData.getText());
            pst.setString(2, txtDescricao.getText());
            pst.setString(3, txtlocal.getText());
            int resultado = pst.executeUpdate();

            if (resultado == 1) {
                JOptionPane.showMessageDialog(null, "Ocorrencia Cadastrada");
                txtData.setText(null);
                txtlocal.setText(null);
                txtDescricao.setText(null);

            } else {
                JOptionPane.showMessageDialog(null, "Ocorrencia nao Cadastrada");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void pesquisar_ocorrencia() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        //String sql = " SELECT COD,NOME,CPF,UF FROM e2cliente WHERE NOME like ? ";
        String sql = " SELECT * FROM e3ocorrencia WHERE COD=?";
   
        try {
             pst = conexao.prepareStatement(sql);
             pst.setString(1, txtCodigo.getText() + "%");
             rs = pst.executeQuery();
             
             tblOcorrencia.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            
        }
    
    
    
    
    
    }

    private void buscar_dados_ocorrencias() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        String sql ="SELECT * FROM e3ocorrencia WHERE descricao like ? ";
       
        try {
             pst = conexao.prepareStatement(sql);
             pst.setString(1, txtDescricao.getText() + "%");
             rs = pst.executeQuery();
            
             tblOcorrencia.setModel(DbUtils.resultSetToTableModel(rs));          
             
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        /**int buscar = tblOcorrencia.getSelectedRow();
        txtCodigo.setText(tblOcorrencia.getModel().getValueAt(buscar,0).toString());
        txtData.setText(tblOcorrencia.getModel().getValueAt(buscar,1).toString());
        txtlocal.setText(tblOcorrencia.getModel().getValueAt(buscar,2).toString());
        txtDescricao.setText(tblOcorrencia.getModel().getValueAt(buscar,3).toString());  **/
    }

    private void consultar() {
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
       String sql ="SELECT * FROM e3ocorrencia WHERE COD=?";
       
        try {
             pst = conexao.prepareStatement(sql);
             pst.setString(1, txtCodigo.getText());
             rs = pst.executeQuery();
            
             if (rs.next()){
             txtCodigo.setText(rs.getString("codigo"));
             txtData.setText(rs.getString("data"));
             txtDescricao.setText(rs.getString("descricao"));
             txtlocal.setText(rs.getString("local"));
             
             }else {
             JOptionPane.showMessageDialog(null, "Ocorrencia nao Localizada");
             txtCodigo.setText(null);
             txtData.setText(null);
             txtDescricao.setText(null);
             txtlocal.setText(null);
             
             }
             
             
             
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }    
    }

    private void remover() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  String sql ="DELETE FROM e3ocorrencia WHERE COD=?";
       
        try {
             pst = conexao.prepareStatement(sql);
             pst.setString(1, txtCodigo.getText());
            // rs = pst.executeQuery();
             
             int apagado = pst.executeUpdate();
            
             if (apagado >0 ){
                JOptionPane.showMessageDialog(null, "Cliente Excluido");
                txtCodigo.setText(rs.getString("codigo"));
                //txtNome.setText(rs.getString("nome"));
                //collocar os demais campos
             
             }
             
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }    
    
    }

    private void atualizar() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        String sql = "UPDATE e3ocorrencia SET data =?, descricao=?, local=? "
                + " WHERE COD=?";

        try {
            pst = conexao.prepareStatement(sql);
            
            pst.setString(1, txtData.getText());
            pst.setString(2, txtDescricao.getText());
            pst.setString(3, txtlocal.getText());
            pst.setString(4, txtCodigo.getText());

            int atualizado = pst.executeUpdate();

            if (atualizado == 1) {
                JOptionPane.showMessageDialog(null, "Ocorrencia Atualizada");
                txtCodigo.setText(null);
                txtlocal.setText(null);
                txtDescricao.setText(null);
                txtData.setText(null);
                
            } else {
                JOptionPane.showMessageDialog(null, "Ocorrencia nao Atualizada");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
        
    }

        /*
    private static class PreparedStatement {

        public PreparedStatement() {
        }

        private void setString(int i, String text) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private int executeUpadate() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }

    private static class ResultSet {

        public ResultSet() {
        }
    }
}
*/
